package MyApp;


/**
* MyApp/Handler.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Handler.idl
* Saturday, June 22, 2019 4:51:00 PM EDT
*/

public interface Handler extends HandlerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Handler
