package MyApp;


/**
* MyApp/HandlerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Handler.idl
* Saturday, June 22, 2019 4:51:00 PM EDT
*/

public abstract class HandlerPOA extends org.omg.PortableServer.Servant
 implements MyApp.HandlerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addEvent", new java.lang.Integer (0));
    _methods.put ("removeEvent", new java.lang.Integer (1));
    _methods.put ("listEventAvailability", new java.lang.Integer (2));
    _methods.put ("bookEvent", new java.lang.Integer (3));
    _methods.put ("cancelEvent", new java.lang.Integer (4));
    _methods.put ("getBookingSchedule", new java.lang.Integer (5));
    _methods.put ("authenEntry", new java.lang.Integer (6));
    _methods.put ("getRequestList", new java.lang.Integer (7));
    _methods.put ("signup", new java.lang.Integer (8));
    _methods.put ("login", new java.lang.Integer (9));
    _methods.put ("swapEvent", new java.lang.Integer (10));
    _methods.put ("shutdown", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MyApp/Handler/addEvent
       {
         String id = in.read_string ();
         String eid = in.read_string ();
         String et = in.read_string ();
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addEvent (id, eid, et, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // MyApp/Handler/removeEvent
       {
         String id = in.read_string ();
         String eid = in.read_string ();
         String et = in.read_string ();
         String $result = null;
         $result = this.removeEvent (id, eid, et);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // MyApp/Handler/listEventAvailability
       {
         String id = in.read_string ();
         String et = in.read_string ();
         String $result = null;
         $result = this.listEventAvailability (id, et);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // MyApp/Handler/bookEvent
       {
         String cid = in.read_string ();
         String mid = in.read_string ();
         String eventId = in.read_string ();
         String et = in.read_string ();
         String $result = null;
         $result = this.bookEvent (cid, mid, eventId, et);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // MyApp/Handler/cancelEvent
       {
         String cid = in.read_string ();
         String mid = in.read_string ();
         String eventId = in.read_string ();
         String et = in.read_string ();
         String $result = null;
         $result = this.cancelEvent (cid, mid, eventId, et);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // MyApp/Handler/getBookingSchedule
       {
         String id = in.read_string ();
         String mid = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (id, mid);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // MyApp/Handler/authenEntry
       {
         String id = in.read_string ();
         String req = in.read_string ();
         String $result = null;
         $result = this.authenEntry (id, req);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // MyApp/Handler/getRequestList
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.getRequestList (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // MyApp/Handler/signup
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.signup (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // MyApp/Handler/login
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.login (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // MyApp/Handler/swapEvent
       {
         String cid = in.read_string ();
         String mid = in.read_string ();
         String neid = in.read_string ();
         String net = in.read_string ();
         String oeid = in.read_string ();
         String oet = in.read_string ();
         String $result = null;
         $result = this.swapEvent (cid, mid, neid, net, oeid, oet);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // MyApp/Handler/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MyApp/Handler:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Handler _this() 
  {
    return HandlerHelper.narrow(
    super._this_object());
  }

  public Handler _this(org.omg.CORBA.ORB orb) 
  {
    return HandlerHelper.narrow(
    super._this_object(orb));
  }


} // class HandlerPOA
