package MyApp;


/**
* MyApp/HandlerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Handler.idl
* Saturday, June 22, 2019 4:51:00 PM EDT
*/

public interface HandlerOperations 
{
  String addEvent (String id, String eid, String et, int capacity);
  String removeEvent (String id, String eid, String et);
  String listEventAvailability (String id, String et);
  String bookEvent (String cid, String mid, String eventId, String et);
  String cancelEvent (String cid, String mid, String eventId, String et);
  String getBookingSchedule (String id, String mid);
  String authenEntry (String id, String req);
  String getRequestList (String id);
  String signup (String id);
  String login (String id);
  String swapEvent (String cid, String mid, String neid, String net, String oeid, String oet);
  void shutdown ();
} // interface HandlerOperations
