package CenterServerIdl;


/**
* CenterServerIdl/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CenterServer.idl
* Monday, July 8, 2019 3:41:12 o'clock PM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
